title: "mitcharoo.com"
description: ""
baseurl: "mitcharoo.com"
url: "https://mitcharoo.com"

header_pages:
  - index.md
  - about.md

style: dark

footer: 'follow on <a href="https://bsky.app/profile/mitcharoo.com">bluesky</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console